### PR TITLE
added terraform security commenter

### PR DESCRIPTION
**Pull request by kilonzi**
## Why

[FE-46](https://broadworkbench.atlassian.net/browse/FE-46)

This PR adds a security commenter to check Terraform files and comment on the issues.
Added:

- [ ] Pre commit hooks for Terraform security check
- [ ] Added instructions how to make these work

[FE-46]: https://broadworkbench.atlassian.net/browse/FE-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by bahill** [comment]
Hey John,
Is this in place of Sourceclear? was this the AppSec recommendation?

**Review by bahill — CHANGES_REQUESTED** [review]
Is this in place of Sourceclear? was this the AppSec recommendation?

**Comment by kilonzi** [comment]
@bahill this won't go to Sourceclear since it's not code that goes to production and Sourceclear doesn't support Terraform files at this time. Our best option would be to use _https://aquasecurity.github.io/tfsec/v1.28.1/_

**Review by bahill — APPROVED** [review]

**Comment by bahill** [comment]
oof - 286 more items to remediate - though I think they overlap a bunch with the other CIS remediations... I'll create a ticket

**Pull request merged**
